name: Deploy HTML to GitHub Pages

on:
  push:
    branches: ["main"]

  # Permitir rodar este workflow manualmente na tela de Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Construir o Site (Gerar a pasta dist)
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer Upload do Arquivo (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fazer o Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
